Repository graphql-python/graphene-django, pull requests merged in 2019-03, with the labels that each got.

#489 Add Introspection Schema Link in Documentation
  docs/tutorial-relay.rst
Labels: 📖 documentation

#477 Ensure code example is fully functional
  docs/tutorial-relay.rst
Labels: ✨enhancement, 📖 documentation

#499 Fix code errors in form-mutations.rst
  docs/form-mutations.rst
Labels: 📖 documentation

#498 Always use HTTPS for CDN files
  graphene_django/templates/graphene/graphiql.html
Labels: security

#439 Allow graphql schema export to use a canonical representation
  docs/introspection.rst
  graphene_django/management/commands/graphql_schema.py
  graphene_django/settings.py
  graphene_django/tests/test_command.py
Labels: changes requested, ✨enhancement

#528 Get queryset
  docs/authorization.rst
  graphene_django/fields.py
  graphene_django/tests/test_query.py
  graphene_django/types.py
Labels: ✨enhancement

#539 Fix duplicated ErrorType declaration
  graphene_django/forms/mutation.py
  graphene_django/rest_framework/mutation.py
  graphene_django/rest_framework/types.py
  graphene_django/tests/issues/__init__.py
  graphene_django/tests/issues/test_520.py
  graphene_django/types.py
Labels: ✨enhancement, 🐛bug
