Repository graphql-python/graphene-django, pull requests merged in 2019-06, with the labels that each got.

#555 Add support for write_only fields in SerializerMutation
  graphene_django/rest_framework/models.py
  graphene_django/rest_framework/mutation.py
  graphene_django/rest_framework/tests/test_mutation.py
Labels: ✨enhancement

#436 Added tox.ini and improved travis.yml
  .gitignore
  .travis.yml
  tox.ini
Labels: changes requested, ✨enhancement

#579 Correctly propagate help_text as description for many-to-* relations
  graphene_django/converter.py
Labels: ✨enhancement

#514 Apply camel case converter to field names in DRF errors
  graphene_django/forms/mutation.py
  graphene_django/forms/tests/test_mutation.py
  graphene_django/rest_framework/mutation.py
  graphene_django/rest_framework/tests/test_mutation.py
  graphene_django/settings.py
  graphene_django/tests/test_utils.py
  graphene_django/types.py
  graphene_django/utils/__init__.py
  graphene_django/utils/utils.py
Labels: help wanted, ✨enhancement
